### ISSUE TITLE
Plugin update and Compatibility check

### ISSUE THREAD

**Issue by dhawalepranav** [rtCamp/rtsocial#125]
We need to complete the following set of tasks for [rtSocial plugin](https://wordpress.org/plugins/rtsocial/).

- [ ]  Make sure it's compatible with latest WordPress version. (e.g 6.4.X )
- [ ]  Make sure it's PHP 8.2 compatible.
- [ ]  Make sure it's VIP compatible
- [ ]  Run the PHPCS scan
- [ ]  Document the user manual with screenshots that will include things like "How to install plugin", "Plugin Pre-requisites" "How to setup plugin for first time", "Plugin Settings with their use case" etc

Before starting the work please add your `Time estimations` for every mentioned task and get it approved by your Project Co-ordinator or Project Manager

**Comment by Pathan-Amaankhan** [comment]
## `~6-7hrs` Testing/Documenting Estimations
- `~1hr` Compatibility test with latest WordPress version & generating report for non-compatible parts/functions.
- `~1hr` Compatibility test with PHP 8.2 & generating report for non-compatible parts/functions.
- `~1hr` Compatibility test with VIP Env & generating report for non-compatible parts/functions.
- `~30mins` Running PHPCS scan & generating report.
- `~2-3hrs` Documenting "Plugin Pre-requisites", "How to setup plugin for first time", "Plugin Settings with their use case" etc.
- `~30mins` Document the user manual with screenshots that will include things like "How to install plugin"
  - I think we already have this one documented -> https://github.com/rtCamp/rtsocial/wiki but still will go through the `wiki` & let you know if anything needs to be updated or a new document needs to be created with estimates.


---

**_Note: The above estimations are for testing/document generation. Once the testing is completed, will share a document containing all the issues & will share an estimate for fixing the found issue (If any)._**


cc: @joelabreo227 @dhawalepranav

**Comment by Pathan-Amaankhan** [comment]
Hello @dhawalepranav,

## Task Updates
- Compatibility test with PHP 8.2 & generating report for non-compatible parts/functions
    - Plugin is compatible with PHP 8.2 & No deprecation was found.
- Running PHPCS scan & generating report.
    - Here are the PHPCS reports (We are having some PHPCS warnings/errors
        - phpcs.xml file scan results: [rtsocial_phpcs_scan.txt](https://github.com/rtCamp/rtsocial/files/13685406/rtsocial_phpcs_scan.txt)
        - WordPress VIP standards scan results: [rtsocial_phpcs_scan_wordpressvip.txt](https://github.com/rtCamp/rtsocial/files/13685438/rtsocial_phpcs_scan_wordpressvip.txt)
- Document the user manual with screenshots that will include things like "How to install plugin", "Plugin Pre-requisites" "How to setup plugin for first time", "Plugin Settings with their use case" etc.
    - The documentation provided in https://github.com/rtCamp/rtsocial/wiki & https://github.com/rtCamp/rtsocial/blob/master/README.md is little outdated. Will update this.


## Tasks W.I.P:
- Compatibility test with latest WordPress version & generating report for non-compatible parts/functions.
- Compatibility test with VIP Env & generating report for non-compatible parts/functions

## PHPCS fix/Documentation updation estimations
- PHPCS fixes
    - [rtsocial_phpcs_scan.txt](https://github.com/rtCamp/rtsocial/files/13685406/rtsocial_phpcs_scan.txt)
        - `~1hr` for fixing issues, raising PRs & merging/testing.
    - [rtsocial_phpcs_scan_wordpressvip.txt](https://github.com/rtCamp/rtsocial/files/13685438/rtsocial_phpcs_scan_wordpressvip.txt)
        - `~2hr` for fixing issues, raising PRs & merging/testing.
- Document the user manual
    - `~2-3hrs` Generating updated documentation.

**Comment by Pathan-Amaankhan** [comment]
Updates:
- Have ran a compatibility test with latest WordPress version & found that our current code is fully compatible with WordPress 6.4.2. ✅ 
- Have ran a compatibility test with VIP Env. & found that our current code is fully compatible with VIP env. ✅ 
- Have updated the [Wiki](https://github.com/rtCamp/rtsocial/wiki) (Updated settings screenshot + removed the additional setting fields from wiki). ✅ 
- PRs fixing PHPCS issues:
    - https://github.com/rtCamp/rtsocial/pull/126
    - https://github.com/rtCamp/rtsocial/pull/127

@dhawalepranav please let me know if we can/should directly merge the PRs on production.

cc: @joelabreo227 @vishalkakadiya

**Comment by Pathan-Amaankhan** [comment]
## Internal Plugin GH workflow

- Sync the plugin’s develop branch with the plugin’s master branch
- Create a PR from develop.
- Do the required changes.
- Merge to develop.

## Internal Plugin Launch Workflow

- Sync the plugin’s develop branch with the plugin’s master branch (if required).
- Test the plugin’s develop branch & see if everything works as expected.
- Create a version update PR against the develop branch.
    - Eg version update PR: https://github.com/rtCamp/rtsocial/pull/106/ 
- Once the PR is approved/merged on develop, create a .zip of the plugin’s develop branch, install the plugin locally, and test if the version is updated and the plugin is working properly.
- Once the plugin’s develop branch is tested thoroughly, raise a `develop to master` sync PR.
    - Eg `develop to master` sync PR: https://github.com/rtCamp/rtsocial/pull/107 
- Once the `develop to master` sync PR is merged, create a .zip of the plugin’s master branch, install the plugin locally, and test if the version is updated and the plugin is working properly.
- Once the plugin’s master branch is tested thoroughly, push the tag from the master branch to release the updated plugin on https://wordpress.org/plugins/.
    - Create the tag: 
        ```
        git tag -a {version-number} -m "Tag Version {version-number}"
        ```
        **_Note: Replace the `{version-number}` with your version._**
    - Push the tag:
        ```
        git push origin {version-number}
        ```
        **_Warning: Pushing this tag will release the WordPress plugin to the wordpress.org plugin repository through GitHub action._**


## References

https://docs.google.com/document/d/1SbJlBe_X78bLY2zD6sTeLqJsc287NwdeICZclVkrb9c/edit 


cc: @dhawalepranav @joelabreo227

**Comment by Pathan-Amaankhan** [comment]
Updates:
We have updated the plugin version on wordpress.org/plugins + made it compatible with `PHP v8.2` & `WordPress v6.4`

cc: @dhawalepranav
