### ISSUE TITLE
rtSocial Plugin - Release Checklist

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/rtsocial#98]
We are about to release the rtSocial plugin, before releasing we need to follow the below checklist.

- [x] Test develop branch thoroughly
- [x] Check the version update PR is reflecting as expected with all fixed changes
- [x] Since this plugin will be released on WP.ORG repo make sure before merging the master everything is tested properly
- [x] Once plugin is released on WP.ORG, check if new version is getting reflected and the plugin is working as expected
- [x] Perform after release steps.

**Comment by pavanpatil1** [comment]
Closing this as this is done.
